### ISSUE TITLE
Automaticaly generate Alerting PrometheusRule based on SRE definition

### ISSUE THREAD

**Issue by Hy3n4** [oskoperator/osko#101]
Creation will be dependent on the SLO annotation.

- Create a template for the Alerting PrometheusRule
- Teach OSKO how to create the APR
- Make sure OSKO can reconcile the created APR

**Comment by fourstepper** [comment]
The "SRE definition" mentioned in the title of this ticket [can be found here](https://sre.google/workbook/alerting-on-slos/#6-multiwindow-multi-burn-rate-alerts)

**Comment by fourstepper** [comment]
Will be closed with https://github.com/oskoperator/osko/pull/127
