### ISSUE TITLE
Create useful manifests examples for development environment

### ISSUE THREAD

**Issue by Hy3n4** [oskoperator/osko#123]
A good idea to start with would be Mimir itself. The metrics should be already there.

**Comment by bliuchak** [comment]
Does it mean that you'll also add an examples how to implement/add OSKO in to existing app? I'm a bit struggling with it :(

**Comment by Hy3n4** [comment]
Not exactly what we meant by this one. This ticket is mainly about OSKO development environment and to have some meaningful source of metrics and SLI/SLOs based on those metrics.

If you have an issue deploying it in your environment feel free to create separate issue (examples and current state of your trying would be helpful) and we will definitely help you solve it.
